[workspace]
members = [
  "noosphere-cbor",
  "noosphere-storage",
  "noosphere-collections",
  "noosphere"
]
# See: https://github.com/rust-lang/rust/issues/90148#issuecomment-949194352
resolver = "2"

